# Generated by Django 4.1 on 2022-08-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_auther',
            new_name='is_auth',
        ),
    ]
